# Generated by Django 4.2.30 on 2026-05-26 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement Data'), ('utility', 'Utility Electricity Data'), ('travel', 'Corporate Travel Data')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed Successfully'), ('failed', 'Ingestion Failed'), ('partial', 'Partially Completed (Some Rows Failed)')], default='completed', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement Data'), ('utility', 'Utility Electricity Data'), ('travel', 'Corporate Travel Data')], max_length=20)),
                ('category', models.CharField(help_text='e.g. Fuel, Electricity, Flight, Hotel, Ground Transport', max_length=50)),
                ('activity_type', models.CharField(help_text='e.g. Diesel, Natural Gas, Grid Electricity, Short-haul Flight', max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('emission_scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct Emissions'), (2, 'Scope 2 - Indirect Emissions (Electricity)'), (3, 'Scope 3 - Value Chain (Corporate Travel)')])),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved (Locked)'), ('rejected', 'Rejected'), ('failed', 'Validation Failed')], default='pending_review', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.TextField(blank=True, help_text='Reasons why validation marked this suspicious.', null=True)),
                ('raw_data', models.JSONField(help_text='Preserved snapshot of the raw messy CSV row for compliance audits.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Analyst justification notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.company')),
                ('source_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.sourceupload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='ingestion_e_company_ae7f46_idx'), models.Index(fields=['company', 'is_suspicious'], name='ingestion_e_company_b4da1e_idx'), models.Index(fields=['source_upload'], name='ingestion_e_source__471c25_idx')],
            },
        ),
    ]
