# Generated by Django 4.2.30 on 2026-05-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_history', to='ingestion.emissionrecord'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['record', 'timestamp'], name='core_auditl_record__58b56b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='core_auditl_perform_13ce27_idx'),
        ),
    ]
